### ISSUE TITLE
Missing targets

### ISSUE THREAD

**Issue by james-yeoman** [marcofugaro/browserslist-to-esbuild#4]
According to [the esbuild docs](https://esbuild.github.io/api/#target), IE and Opera are supported targets, but [`SUPPORTED_ESBUILD_TARGETS`](https://github.com/marcofugaro/browserslist-to-esbuild/blob/23d12558733a2474412c5897c0a64518127bca40/src/index.js#L14) doesn't contain IE nor Opera.

Also, Samsung Internet [is chromium-based](https://en.wikipedia.org/wiki/Samsung_Internet#History), so could be mapped.

**Comment by marcofugaro** [comment]
They added them recently, are you willing to make a PR?

**Comment by ashleigh-yeoman** [comment]
Sure

**Comment by ashleigh-yeoman** [comment]
@marcofugaro is it ok if I add a tweak in my PR? Or should I make it a separate PR?

You've currently got browserslist listed as a dependency, which means that even if people use a different browserslist (e.g. if browserslist updates and they have the latest browserslist), browserslist-to-esbuild will still be using the old definitions.

~~Also, the tests are failing, even when I do `npm ci`~~
EDIT: nvm about the tests, that was just because of the shifting that occurs when including IE and Opera

**Comment by marcofugaro** [comment]
Oh yeah you're right, browserslist should be a peerDependency.
Yes, different PR if you can, thanks

**Comment by marcofugaro** [comment]
I've added Opera and IE support in c79373569a8c3ec5527b149666997b06f2d83552.

However I've decided not to support Samsung Internet since esbuild doesn't support it. 
Also it's not a 1:1 conversion to the Chrome browser regarding features, for this reason the solution you implemented in #5 may lead to some confusion.
I'll add support for it if esbuild does though!
